# Generated by Django 3.0.1 on 2020-02-24 12:08

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelname', models.CharField(max_length=100, verbose_name='Name_of_label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Name_of_Note')),
                ('note', models.TextField(verbose_name='Enter_note_here')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('is_archieved', models.BooleanField(default=False, verbose_name='is_archieved')),
                ('is_trashed', models.BooleanField(default=False, verbose_name='is_trashed')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='is_pinned')),
                ('remender', models.DateTimeField(blank=True, null=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('collabrator', models.ManyToManyField(related_name='Collabrator_of_note', to=settings.AUTH_USER_MODEL)),
                ('label', models.ManyToManyField(related_name='label_of_note', to='Note.Label')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
