# Generated by Django 3.0.1 on 2020-02-24 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='collabrator',
            field=models.ManyToManyField(blank=True, related_name='Collabrator_of_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label_of_note', to='Note.Label'),
        ),
    ]
