# Generated by Django 3.0.1 on 2020-02-25 04:12

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_auto_20200224_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, colors=['#FF0000', '#00FF00', '#0000FF'], null=True),
        ),
    ]
