# Generated by Django 3.0.3 on 2020-02-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loginregistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password1',
            new_name='conformpassword',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='password2',
            new_name='password',
        ),
    ]
